# Site settings
title: damiankloip.net
email:
description:
# the subpath of your site, e.g. /blog/
baseurl: ""
# the base hostname & protocol for your site
url: "http://damiankloip.net"
twitter_username: damiankloip
github_username:  damiankloip

# Build settings
markdown: kramdown
permalink: /:year/:title
excerpt_separator: <!--more-->